GET http://localhost:3000/favorites.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc3Mjk0ODF9.SvYWTozdTyuJN5Vf7ksAM92lXDXt1wPlvPBL6tgF7Ek
###

DELETE http://localhost:3000/favorites/18
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc2NDI0MzB9.pqCpnvvI0MDgn7hAxMGatnboWSihYF-d8a3r2P-ynw4

###

POST http://localhost:3000/favorites.json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTc3Mjk0ODF9.SvYWTozdTyuJN5Vf7ksAM92lXDXt1wPlvPBL6tgF7Ek
Content-Type: application/json

{
  "anime_id": 1,
  "user_id": 1
}
