### Index
GET http://localhost:3000/mangas.json


### Show
GET http://localhost:3000/mangas/1.json


### Create
POST http://localhost:3000/mangas.json
Content-Type: application/json

{
  "name": "Test",
  "chapter": 1096,
  "volume": 101,
  "description": "The story follows the adventures of Shinichi Kudo a young detective prodigy who was inadvertently shrunk into a child's body due to a poison he was force-fed by members of a criminal syndicate."
}
### images create

POST http://localhost:3000/images.json
Content-Type: application/json

{
  "url": "detectiveConan.jpg",
  "manga_id": 11

}
### where to reads cerate
POST http://localhost:3000/manga_wheres.json
Content-Type: application/json

{
  "where_to_read_id": 1,
  "manga_id": 2,
  "url_manga": "test.jpg"

}


### UPDATE action

PATCH http://localhost:3000/mangas/1.json
Content-Type: application/json

{
  "manga_url": "https://www.viz.com/shonenjump/chapters/one-piece?locale=en"
}

###
DELETE http://localhost:3000/images/2